export const Players = [
  {
    image: "https://static.iplt20.com/players/210/1.png",
    Name: "M.S.Dhoni",
    Country: "India",
    Matches: "215",
    Innings: "190",
    Runs: "4698",
    HighScore: "84",
    Avg: "39.8",
    StrikeRate: "136.3",
    Catches: "123",
    Hundreds: "0",
    Fifties: "23",
    Fours: "320",
    Sixes: "218",
    Skills: "Right Hand Batsman,Wicket Keeper",
  },
  {
    image: "https://static.iplt20.com/players/210/24.png",
    Name: "Faf du Plessis",
    Country: "South-Africa",
    Matches: "95",
    Innings: "88",
    Runs: "2737",
    HighScore: "96",
    Avg: "34.64",
    StrikeRate: "130.58",
    Catches: "100",
    Hundreds: "0",
    Fifties: "20",
    Fours: "246",
    Sixes: "90",
    Skills: "Right Hand Batsman",
  },
  {
    image: "https://static.iplt20.com/players/210/14.png",
    Name: "Suresh Raina",
    Country: "India",
    Matches: "204",
    Innings: "199",
    Runs: "5525",
    HighScore: "100",
    Avg: "32.69",
    StrikeRate: "136.82",
    Catches: "110",
    Hundreds: "1",
    Fifties: "39",
    Fours: "506",
    Sixes: "203",
    Skills: "Left Hand Batsman",
  },
  {
    image: "https://static.iplt20.com/players/210/100.png",
    Name: "Ambati Rayudu",
    Country: "India",
    Matches: "170",
    Innings: "160",
    Runs: "3854",
    HighScore: "100",
    Avg: "29.64",
    StrikeRate: "127.73",
    Catches: "56",
    Hundreds: "1",
    Fifties: "20",
    Fours: "319",
    Sixes: "147",
    Skills: "Right Hand Batsman",
  },
  {
    image: "https://static.iplt20.com/players/210/5443.png",
    Name: "Ruturaj Gaikwad",
    Country: "India",
    Matches: "17",
    Innings: "17",
    Runs: "1000",
    HighScore: "100",
    Avg: "43.8",
    StrikeRate: "129.3",
    Catches: "10",
    Hundreds: "1",
    Fifties: "6",
    Fours: "60",
    Sixes: "21",
    Skills: "Right Hand Batsman",
  },
  {
    image: "https://static.iplt20.com/players/210/9.png",
    Name: "R.Jadeja",
    Country: "India",
    Matches: "195",
    Innings: "147",
    Runs: "2338",
    HighScore: "62",
    Avg: "26.8",
    StrikeRate: "127.89",
    Catches: "120",
    Hundreds: "0",
    Fifties: "2",
    Fours: "171",
    Sixes: "84",
    Skills: "All-Rounder",
  },
  {
    image: "https://static.iplt20.com/players/210/25.png",
    Name: "Dwayne Bravo",
    Country: "West Indies",
    Matches: "147",
    Innings: "106",
    Runs: "1533",
    HighScore: "70",
    Avg: "22.88",
    StrikeRate: "130.3",
    Catches: "87",
    Hundreds: "0",
    Fifties: "05",
    Fours: "118",
    Sixes: "65",
    Skills: "All-Rounder",
  },
  {
    image: "https://static.iplt20.com/players/210/1735.png",
    Name: "Moeen Ali",
    Country: "England",
    Matches: "29",
    Innings: "27",
    Runs: "650",
    HighScore: "66",
    Avg: "23.8",
    StrikeRate: "149.7",
    Catches: "12",
    Hundreds: "0",
    Fifties: "04",
    Fours: "47",
    Sixes: "38",
    Skills: "All-Rounder",
  },
  {
    image: "https://cdn.wisden.com/wp-content/uploads/2020/09/Sam-curran.png",
    Name: "Sam Curran",
    Country: "England",
    Matches: "31",
    Innings: "23",
    Runs: "400",
    HighScore: "55",
    Avg: "22.8",
    StrikeRate: "149.8",
    Catches: "15",
    Hundreds: "0",
    Fifties: "2",
    Fours: "30",
    Sixes: "18",
    Skills: "All-Rounder",
  },
  {
    image: "https://static.iplt20.com/players/210/140.png",
    Name: "Deepak Chahar",
    Country: "India",
    Matches: "59",
    Innings: "58",
    Runs: "79",
    HighScore: "56",
    Avg: "18.8",
    StrikeRate: "22.3",
    Catches: "123",
    Hundreds: "0",
    Fifties: "0",
    Fours: "4",
    Sixes: "1",
    Skills: "Bowler",
  },
  {
    image: "https://static.iplt20.com/players/210/1745.png",
    Name: "Shardul Thakur",
    Country: "India",
    Matches: "56",
    Innings: "55",
    Runs: "58",
    HighScore: "57",
    Avg: "10.8",
    StrikeRate: "20.3",
    Catches: "42",
    Hundreds: "0",
    Fifties: "0",
    Fours: "5",
    Sixes: "1",
    Skills: "Bowlerr",
  },
  {
    image: "https://static.iplt20.com/players/210/898.png",
    Name: "Mohammad Imran Tahir",
    Country: "South Africa",
    Matches: "59",
    Innings: "55",
    Runs: "50",
    HighScore: "82",
    Avg: "20.8",
    StrikeRate: "13.3",
    Catches: "42",
    Hundreds: "0",
    Fifties: "0",
    Fours: "5",
    Sixes: "0",
    Skills: "Bowler",
  },
  {
    image: "https://static.iplt20.com/players/210/1903.png",
    Name: "Mitchell Josef Santner",
    Country: "NewZeland",
    Matches: "6",
    Innings: "6",
    Runs: "40",
    HighScore: "6",
    Avg: "20.8",
    StrikeRate: "21.3",
    Catches: "2",
    Hundreds: "0",
    Fifties: "0",
    Fours: "3",
    Sixes: "0",
    Skills: "Bowler",
  },
  {
    image: "https://static.iplt20.com/players/210/3746.png",
    Name: "Lungi Ngidi",
    Matches: "15",
    Innings: "14",
    Runs: "0",
    HighScore: "25",
    Avg: "17.8",
    StrikeRate: "13.3",
    Catches: "4",
    Hundreds: "0",
    Fifties: "0",
    Fours: "0",
    Sixes: "0",
    Skills: "Bowler",
  },
  {
    image: "https://static.iplt20.com/players/210/3834.png",
    Name: "Krishnappa Gowtham",
    Matches: "12",
    Innings: "10",
    Runs: "200",
    HighScore: "33",
    Avg: "15.8",
    StrikeRate: "162.3",
    Catches: "2",
    Hundreds: "00",
    Fifties: "01",
    Fours: "13",
    Sixes: "12",
    Skills: "All-Rounder",
  },
  {
    image: "https://static.iplt20.com/players/210/156.png",
    Name: "Chateswar Pujara",
    Matches: "30",
    Innings: "23",
    Runs: "400",
    HighScore: "51",
    Avg: "20.8",
    StrikeRate: "99.3",
    Catches: "5",
    Hundreds: "0",
    Fifties: "1",
    Fours: "50",
    Sixes: "4",
    Skills: "Right Hand Batsman",
  },
];
